[book]
authors = []
title = "LibreScan - documentation"
language = "en"
multilingual = false
src = "src"

[output.html]
git-repository-url = "https://github.com/librescan-org/docs/tree/main/"
edit-url-template = "https://github.com/librescan-org/docs/edit/main/{path}"
